// GENERATED by scripts/gen-tools.mjs — do not edit.
// Source: ../api/openapi.yaml (flat 1:1 operations) + the manifest in scripts/gen-tools.mjs.
// Composites, SSE, and session state stay hand-written in the other src/tools/*.ts.
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { Ctx } from "../context.js";
import { isPropertyName } from "../api/property-names.js";
import { apiMessage, ToolError } from "../errors.js";
import { defineTool, textResult } from "./helpers.js";

/** Register the generated flat 1:1 tools. */
export function register(server: McpServer, ctx: Ctx): void {
  defineTool(
    server,
    "get_property",
    "Read one property with available_values + writability. name is a slug discovered from get_camera_state (e.g. iso, aperture, shutter-speed).",
    {
      name: z.string(),
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      if (!isPropertyName(args.name)) throw new ToolError(`get_property(${args.name}) failed: unknown property slug; see get_camera_state for valid names.`);
      let res;
      try {
        res = await ctx.client.properties.get({ cameraId, propertyName: args.name });
      } catch (e) {
        throw new ToolError(`get_property(${args.name}) failed: ${apiMessage(e)}`);
      }
      return textResult(res);
    },
  );

  defineTool(
    server,
    "half_press",
    "S1 half-press to lock AF without firing.",
    {
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      let res;
      try {
        res = await ctx.client.actions.halfPress({ cameraId });
      } catch (e) {
        throw new ToolError(`half_press failed: ${apiMessage(e)}`);
      }
      return textResult(res);
    },
  );

  defineTool(
    server,
    "focus_step",
    "Discrete manual-focus nudge: -7 (near, fast) to +7 (far, fast); magnitude = speed. 0 is invalid. The primitive for a look->step->look loop.",
    {
      step: z.number().int(),
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      if (args.step === 0 || args.step < -7 || args.step > 7) throw new ToolError("step must be -7..-1 or +1..+7 (0 is invalid).");
      let res;
      try {
        res = await ctx.client.actions.focusNearFar({ cameraId, step: args.step });
      } catch (e) {
        throw new ToolError(`focus_step failed: ${apiMessage(e)} (check the lens MF switch and that focus-near-far is enabled).`);
      }
      return textResult(res);
    },
  );

  defineTool(
    server,
    "zoom",
    "Power-zoom control (requires a power-zoom lens). direction: wide/tele (or in/out); speed 1-8.",
    {
      direction: z.enum(["wide", "tele", "in", "out"]),
      speed: z.number().int().default(3),
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      const signed = args.direction === "tele" || args.direction === "in" ? Math.abs(args.speed) : -Math.abs(args.speed);
      let res;
      try {
        res = await ctx.client.actions.zoom({ cameraId, body: { speed: signed } });
      } catch (e) {
        throw new ToolError(`zoom failed: ${apiMessage(e)}`);
      }
      return textResult(res);
    },
  );

  defineTool(
    server,
    "toggle_movie_rec",
    "Start/stop movie recording (server toggles). Camera must be in a movie mode.",
    {
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      let res;
      try {
        res = await ctx.client.actions.movieRec({ cameraId });
      } catch (e) {
        throw new ToolError(`toggle_movie_rec failed: ${apiMessage(e)}`);
      }
      return textResult(res);
    },
  );

  defineTool(
    server,
    "get_save_config",
    "Read host save-path config (where auto-transferred files land).",
    {
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      let res;
      try {
        res = await ctx.client.settings.getSaveInfo({ cameraId });
      } catch (e) {
        throw new ToolError(`get_save_config failed: ${apiMessage(e)}`);
      }
      return textResult(res);
    },
  );

  defineTool(
    server,
    "set_save_config",
    "Set host save path / naming for auto-transferred captures.",
    {
      path: z.string().optional(),
      prefix: z.string().optional(),
      start_no: z.number().int().optional(),
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      let res;
      try {
        res = await ctx.client.settings.setSaveInfo({ cameraId, path: args.path, prefix: args.prefix, startNo: args.start_no });
      } catch (e) {
        throw new ToolError(`set_save_config failed: ${apiMessage(e)}`);
      }
      return textResult(res);
    },
  );

  defineTool(
    server,
    "snapshot_camera_settings",
    "Download the camera's full settings to a host file (save a reusable config).",
    {
      filename: z.string().optional(),
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      let res;
      try {
        res = await ctx.client.settings.download({ cameraId, body: { filename: args.filename } });
      } catch (e) {
        throw new ToolError(`snapshot failed: ${apiMessage(e)}`);
      }
      return textResult(res);
    },
  );

  defineTool(
    server,
    "restore_camera_settings",
    "Upload a previously saved settings file back to the camera (overwrites live config).",
    {
      filename: z.string(),
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      let res;
      try {
        res = await ctx.client.settings.upload({ cameraId, body: { filename: args.filename } });
      } catch (e) {
        throw new ToolError(`restore failed: ${apiMessage(e)}`);
      }
      return textResult(res);
    },
  );

  defineTool(
    server,
    "list_settings_files",
    "List saved camera-settings files on the host.",
    {
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      let res;
      try {
        res = await ctx.client.settings.listFiles({ cameraId });
      } catch (e) {
        throw new ToolError(`list_settings_files failed: ${apiMessage(e)}`);
      }
      return textResult(res);
    },
  );

  defineTool(
    server,
    "import_lut",
    "Import a LUT to the camera (niche; faithful passthrough).",
    {
      file_path: z.string(),
      slot: z.number().int().optional(),
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      let res;
      try {
        res = await ctx.client.settings.importLut({ cameraId, filePath: args.file_path, slot: args.slot });
      } catch (e) {
        throw new ToolError(`import_lut failed: ${apiMessage(e)}`);
      }
      return textResult(res);
    },
  );

  defineTool(
    server,
    "list_captures",
    "List SD-card files for a slot. Requires remote-transfer or contents mode.",
    {
      slot: z.number().int().default(1),
      camera_id: z.string().optional(),
    },
    async (args) => {
      const cameraId = ctx.resolveCamera(args.camera_id);
      let res;
      try {
        res = await ctx.client.sdCard.list({ cameraId, slotNumber: args.slot });
      } catch (e) {
        throw new ToolError(`list_captures failed: ${apiMessage(e)}${ctx.state.mode === "remote" ? " (reconnect in remote-transfer or contents mode)" : ""}`);
      }
      return textResult(res);
    },
  );
}
